require 'echoe'
Echoe.new('avro') do |p|
  p.author = "Jeff Hodges"
  p.author = "Ryan King"
  p.summary = "Apache Avro for Ruby"
  p.url = "http://hadoop.apache.org/avro/"
  p.runtime_dependencies = %w[rubygems yajl]
end